/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventWithRelations } from './eventWithRelations';


/**
 * (tsType: EventDayWithRelations, schemaOptions: { includeRelations: true })
 */
export interface EventDayWithRelations { 
  [key: string]: object | any;


    id?: string;
    date: string;
    eventId?: string;
    event?: EventWithRelations;
}

