/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventIncludeFilterItems } from './eventIncludeFilterItems';
import { EventFields } from './eventFields';


export interface EventFilter1 { 
    offset?: number;
    limit?: number;
    skip?: number;
    order?: string | Array<string>;
    where?: { [key: string]: object; };
    fields?: EventFields;
    include?: Array<EventIncludeFilterItems>;
}

