/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<EventDay, \'id\'>, \'eventId\'>, schemaOptions: { title: \'NewEventDayInEvent\', exclude: [ \'id\' ], optional: [ \'eventId\' ] })
 */
export interface NewEventDayInEvent { 
  [key: string]: object | any;


    date: string;
    eventId?: string;
}

