/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Option, \'id\'>, \'eventDayId\'>, schemaOptions: { title: \'NewOptionInEventDay\', exclude: [ \'id\' ], optional: [ \'eventDayId\' ] })
 */
export interface NewOptionInEventDay { 
    emailVotante?: string;
    eventDayId?: string;
}

