/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Option, \'id\'>, schemaOptions: { title: \'NewOption\', exclude: [ \'id\' ] })
 */
export interface NewOption { 
    fecha: string;
    eventId?: string;
    emailVotante?: string;
}

