/**
 * event-apirest
 * ingapp
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Option, \'id\'>, \'eventId\'>, schemaOptions: { title: \'NewOptionInEvent\', exclude: [ \'id\' ], optional: [ \'eventId\' ] })
 */
export interface NewOptionInEvent { 
    fecha?: string;
    eventId?: string;
    emailVotante?: string;
}

